### ISSUE TITLE
ERROR when use mediator

### ISSUE THREAD

**Issue by yonger001** [XiaohangZhan/cdp#11]
Hi, when I run mediator ,there is a error as following:
1. 
Creating pair set for: labeled
	Loading features
	Loading base KNN
	Loading committee KNN
	Loading pairs
	got 4813844 pairs
	relationship features exist
	getting affinity features
		processing: 0/5
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    main()
  File "main.py", line 45, in main
    cdp(args)
  File "/media/syl/BIG_ONE/cdp-master/source/cdp.py", line 77, in cdp
    pairs, scores = mediator(args)
  File "/media/syl/BIG_ONE/cdp-master/source/cdp.py", line 172, in mediator
    create(args.mediator['train_data_name'], args, phase="train")
  File "/media/syl/BIG_ONE/cdp-master/source/create_pair_set.py", line 137, in create
    affinity_feat = get_affinity_feat(features, pairs)
  File "/media/syl/BIG_ONE/cdp-master/source/create_pair_set.py", line 33, in get_affinity_feat
    cosine_simi.append(cosine_similarity(feat[pairs[:,0],:], feat[pairs[:,1],:]))
  File "/media/syl/BIG_ONE/cdp-master/source/create_pair_set.py", line 24, in cosine_similarity
    feat1 /= np.linalg.norm(feat1, axis=1).reshape(-1, 1)
  File "/usr/local/lib/python3.5/dist-packages/numpy/linalg/linalg.py", line 2480, in norm
    s = (x.conj() * x).real
MemoryError

2. when I remove affinity form yaml, there is a new error,
  false_pos = ((pred == 1) & (label == 0)).sum() / float((pred == 1).sum())
Testing set. acc: 0.9997, abs_recall: 0, rel_recall: 0, false_pos: nan, false_neg: 0.0002552
	pair num: 0
Propagation ...
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    main()
  File "main.py", line 45, in main
    cdp(args)
  File "/media/syl/BIG_ONE/cdp-master/source/cdp.py", line 84, in cdp
    components = graph.graph_propagation(pairs, scores, args.propagation['max_sz'], args.propagation['step'])
  File "/media/syl/BIG_ONE/cdp-master/source/graph.py", line 81, in graph_propagation
    th = score.min()
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

Do you have some idea? Wiating for ur reply, thank you very much!

**Comment by XiaohangZhan** [comment]
1. buy more memory bars or use less data.
2. decrease the threshold.
